---
version: "3"

services:

  # T
  telegraf:
    image: telegraf:1.2.1-alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allow Docker plugin to read events

  # I
  influxdb:
    image: influxdb:1.2.2-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro

  # C
  chronograf:
    image: quay.io/influxdb/chronograf:1.2.0-beta8
    ports:
      - "8888:8888"
    volumes:
      - ./chronograf.conf:/etc/chronograf/chronograf.conf:ro
      - ./chronograf-v1.db:/var/lib/chronograf/chronograf-v1.db:rw

  # K
  kapacitor:
    image: kapacitor:1.2.0-alpine
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro

# ------------------------------------------------------------------------------
  # Grafana - not part of the TICK-stack but usually used togheter with InfluxDB
  grafana:
    image: grafana/grafana:4.2.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana:rw

# ------------------------------------------------------------------------------

